services:
  - type: web
    name: admin-application
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    buildFilter:
      paths:
        - .

